In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sn

In [2]:
data = pd.read_csv("Data_ML_assurance.csv")
data

Gravblessure_Usager  Collision_Acc  Sexe_Usager  \
0                         1            4.0            1   
1                         1            4.0            1   
2                         1            4.0            1   
3                         1            4.0            1   
4                         1            4.0            1   
...                     ...            ...          ...   
253483                    1            4.0            1   
253484                    1            4.0            1   
253485                    4            4.0            1   
253486                    4            4.0            1   
253487                    4            4.0            1   

        Anne_Naissance_Usager  Equipement_Secu_Usager Commune_Acc  \
0                        1993                     1.0       94069   
1                        1993                     1.0       94069   
2                        1993                     1.0       94069   
3                        1968                     1.0       94069   
4                        1968                     1.0       94069   
...                       ...                     ...         ...   
253483                   1968                     1.0       13071   
253484                   1968                     1.0       13071   
253485                   1964                     1.0       13071   
253486                   1964                     1.0       13071   
253487                   1964                     1.0       13071   

        Equipement_Secu_Usager.1  Categorie_Vehicule  \
0                            1.0                   7   
1                            1.0                   7   
2                            1.0                   7   
3                            1.0                   7   
4                            1.0                   7   
...                          ...                 ...   
253483                       1.0                  10   
253484                       1.0                   7   
253485                       1.0                  10   
253486                       1.0                  10   
253487                       1.0                   7   

        Type_motorisation_Vehicule  Nb_occupant_Vehicule  ...  \
0                              1.0                   NaN  ...   
1                              1.0                   NaN  ...   
2                              1.0                   NaN  ...   
3                              1.0                   NaN  ...   
4                              1.0                   NaN  ...   
...                            ...                   ...  ...   
253483                         1.0                   NaN  ...   
253484                         1.0                   NaN  ...   
253485                         1.0                   NaN  ...   
253486                         1.0                   NaN  ...   
253487                         1.0                   NaN  ...   

        Circulation_Route  Nb_voie_Route  Vitesse_max_Route  Surface_Route  \
0                     3.0              5               90.0            1.0   
1                     3.0              5               90.0            1.0   
2                     3.0              5               90.0            1.0   
3                     3.0              5               90.0            1.0   
4                     3.0              5               90.0            1.0   
...                   ...            ...                ...            ...   
253483                3.0              2              110.0            1.0   
253484                3.0              2              110.0            1.0   
253485                3.0              2              110.0            1.0   
253486                3.0              2              110.0            1.0   
253487                3.0              2              110.0            1.0   

        Categorie_Vehicule.1             Date_Acc Lumiere_Acc  Meteo_Acc  \
0  

In [4]:
data["Collision_Acc"].value_counts(normalize=True)

3.0    0.318361
6.0    0.161524
2.0    0.141838
4.0    0.126516
1.0    0.110113
5.0    0.107473
7.0    0.034175
Name: Collision_Acc, dtype: float64

In [6]:
data["Gravblessure_Usager"].value_counts(normalize=True)

1    0.449970
4    0.394745
3    0.133880
2    0.021405
Name: Gravblessure_Usager, dtype: float64

In [3]:
data.columns

Index(['Gravblessure_Usager', 'Collision_Acc', 'Sexe_Usager',
       'Anne_Naissance_Usager', 'Equipement_Secu_Usager', 'Commune_Acc',
       'Equipement_Secu_Usager.1', 'Categorie_Vehicule',
       'Type_motorisation_Vehicule', 'Nb_occupant_Vehicule', 'Categorie_Route',
       'Circulation_Route', 'Nb_voie_Route', 'Vitesse_max_Route',
       'Surface_Route', 'Categorie_Vehicule.1', 'Date_Acc', 'Lumiere_Acc',
       'Meteo_Acc', 'Motif_Deplacer_Usager', 'Departement_Acc'],
      dtype='object')

In [7]:
data["Date_Acc"] = pd.to_datetime(data["Date_Acc"])
data["Month"] = data["Date_Acc"].dt.month

In [8]:
data["Age"] = 2019 - data["Anne_Naissance_Usager"]

In [9]:
data.loc[data["Vitesse_max_Route"] > 130, "Vitesse_max_Route"] = data.loc[data["Vitesse_max_Route"] > 130, "Vitesse_max_Route"].apply(lambda x: x/10)

In [10]:
data.loc[data["Vitesse_max_Route"] < 10, "Vitesse_max_Route"] = data["Vitesse_max_Route"][data["Vitesse_max_Route"] < 10] * 10

In [11]:
data["Motif_Deplacer_Usager"].value_counts()

5.0    95352
1.0    34837
4.0    25741
9.0    18005
3.0     5980
2.0     4583
Name: Motif_Deplacer_Usager, dtype: int64

In [12]:
data["Motif_Deplacer_Usager"].isna().sum()

68990

In [13]:
data["Month"].value_counts(normalize=True)

7     0.094265
6     0.093720
10    0.092028
9     0.089551
12    0.086288
11    0.084801
5     0.080765
8     0.079282
3     0.078631
4     0.078039
1     0.071802
2     0.070828
Name: Month, dtype: float64

In [11]:
from sklearn.linear_model import LogisticRegression, SGDClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.neighbors import KNeighborsClassifier
from sklearn.manifold import TSNE
from sklearn.metrics import accuracy_score,precision_score,confusion_matrix,classification_report, precision_recall_curve

In [12]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split, GridSearchCV

C = 10
# Create different classifiers.
classifiers = {
#    'SGD Logistic': SGDClassifier(alpha=0.0001, max_iter=2000, loss="log"),
#    'Linear SVC': SVC(kernel='linear', C=C, probability=True,random_state=0),
#    'KNN classifier': KNeighborsClassifier(C),
#    'SVC': SVC(),
    'RFST': RandomForestClassifier(n_estimators=100),
    'ADA': AdaBoostClassifier(n_estimators=100)
}

num_attribs = ["Age", "Nb_voie_Route", "Vitesse_max_Route"]
cat_attribs = ["Sexe_Usager", "Equipement_Secu_Usager", "Departement_Acc", "Categorie_Vehicule", "Month", "Type_motorisation_Vehicule", "Categorie_Route", "Circulation_Route", "Surface_Route", "Lumiere_Acc", "Meteo_Acc", "Motif_Deplacer_Usager"]

num_pipeline = Pipeline([
        ('std_scaler', StandardScaler()),
    ])

full_pipeline = ColumnTransformer([
        ("num", num_pipeline, num_attribs),
        ("cat", OneHotEncoder(), cat_attribs),
    ])

In [37]:
def train_model(x_train, y_train, x_test, y_test, output=True, filter=None, classifiers={ 'SGD Logistic': SGDClassifier(alpha=0.0001, max_iter=2000, loss="log"), 'Linear SVC': SVC(kernel='linear', C=C, probability=True,random_state=0), 'KNN classifier': KNeighborsClassifier(C), 'SVC': SVC(), 'RFST': RandomForestClassifier(n_estimators=100), 'ADA': AdaBoostClassifier(n_estimators=100) }):
    X_train = full_pipeline.fit_transform(x_train)

    X_test = full_pipeline.transform(x_test)

    n_classifiers = len(classifiers)
    acc_list = []

    for index, (name, classifier) in enumerate(classifiers.items()):
        if (filter is not None and name not in filter):
            continue
        classifier.fit(X_train, np.ravel(y_train))

        y_pred = classifier.predict(X_test)
        accuracy = accuracy_score(y_test, y_pred)
        acc_list.append(accuracy)
        if (output == True or isinstance(output, list)):
            if (output == True or "accuracy" in output):
                print("Accuracy (train) for %s: %0.1f%% " % (name, accuracy * 100))
            if (output == True or "report" in output):
                print(classification_report(y_test, y_pred))
            if (output == True or "matrix" in output):
                print(confusion_matrix(y_test, y_pred))
    return acc_list, y_pred

In [14]:
data_train = data[num_attribs + cat_attribs + ["Gravblessure_Usager"]].copy()

In [15]:
data_train.dropna(inplace=True)

In [16]:
data_train.reset_index(drop=True, inplace=True)

In [16]:
X_train, X_test, y_train, y_test = train_test_split(data_train[num_attribs + cat_attribs], data_train["Gravblessure_Usager"], test_size=0.33, random_state=42)

In [18]:
train_model(X_train, y_train, X_test, y_test)

Accuracy (train) for RFST: 77.2% 
              precision    recall  f1-score   support

           1       0.81      0.87      0.84     25673
           2       0.74      0.29      0.41      1350
           3       0.69      0.55      0.61      8269
           4       0.75      0.77      0.76     21645

    accuracy                           0.77     56937
   macro avg       0.75      0.62      0.66     56937
weighted avg       0.77      0.77      0.77     56937

[[22362    33   497  2781]
 [  273   388   442   247]
 [ 1244    68  4586  2371]
 [ 3816    35  1160 16634]]
Accuracy (train) for ADA: 60.1% 
              precision    recall  f1-score   support

           1       0.62      0.81      0.70     25673
           2       0.36      0.02      0.03      1350
           3       0.48      0.30      0.37      8269
           4       0.60      0.51      0.55     21645

    accuracy                           0.60     56937
   macro avg       0.52      0.41      0.41     56937
weighted 

([0.7722570560444, 0.6008395243866027],
 array([1, 4, 4, ..., 1, 3, 1], dtype=int64))

In [18]:
def train_model_grid(x_train, y_train, output=True):
    X_train = full_pipeline.fit_transform(x_train)
    param_grid = { 
        'n_estimators': [200, 500],
        'max_features': ['auto', 'sqrt', 'log2'],
        'max_depth': [4,5,6,7,8],
        'criterion': ['gini', 'entropy']
    }
    rfc = RandomForestClassifier(random_state=42)
    CV_rfc = GridSearchCV(estimator=rfc, param_grid=param_grid, cv= 5)
    CV_rfc.fit(X_train, y_train)
    print(CV_rfc.best_params_)
    return CV_rfc.best_params_

In [32]:
from sklearn.model_selection import StratifiedShuffleSplit

split = StratifiedShuffleSplit(n_splits=1,
                               test_size=0.3, random_state=42)
for train_index, test_index in split.split(data_train, data_train["Gravblessure_Usager"]):
    strat_train_set = data_train.loc[train_index]
    strat_test_set = data_train.loc[test_index]

In [33]:
X_train, X_test, y_train, y_test = train_test_split(strat_test_set, strat_test_set["Gravblessure_Usager"], test_size=0.33, random_state=42)

In [34]:
train_model(X_train, y_train, X_test, y_test)

Accuracy (train) for RFST: 66.9% 
              precision    recall  f1-score   support

           1       0.71      0.80      0.76      7811
           2       0.48      0.10      0.16       402
           3       0.54      0.37      0.44      2378
           4       0.64      0.65      0.65      6491

    accuracy                           0.67     17082
   macro avg       0.59      0.48      0.50     17082
weighted avg       0.66      0.67      0.66     17082

[[6287    8  229 1287]
 [  94   40  157  111]
 [ 527   22  889  940]
 [1890   14  383 4204]]
Accuracy (train) for ADA: 60.1% 
              precision    recall  f1-score   support

           1       0.63      0.80      0.70      7811
           2       0.13      0.02      0.04       402
           3       0.48      0.31      0.38      2378
           4       0.59      0.51      0.55      6491

    accuracy                           0.60     17082
   macro avg       0.46      0.41      0.42     17082
weighted avg       0.58  

([0.6685399836084768, 0.6009249502400187],
 array([1, 1, 1, ..., 1, 4, 1], dtype=int64))

In [35]:
train_model_grid(X_train, y_train)

{'criterion': 'gini', 'max_depth': 8, 'max_features': 'auto', 'n_estimators': 200}


{'criterion': 'gini',
 'max_depth': 8,
 'max_features': 'auto',
 'n_estimators': 200}

In [39]:
X_train, X_test, y_train, y_test = train_test_split(data_train[num_attribs + cat_attribs], data_train["Gravblessure_Usager"], test_size=0.33, random_state=42)

In [43]:
model = RandomForestClassifier(n_estimators=200)
train_model(X_train, y_train, X_test, y_test, classifiers={'RFST': model})

Accuracy (train) for RFST: 77.3% 
              precision    recall  f1-score   support

           1       0.81      0.87      0.84     25673
           2       0.75      0.28      0.41      1350
           3       0.69      0.56      0.61      8269
           4       0.76      0.77      0.76     21645

    accuracy                           0.77     56937
   macro avg       0.75      0.62      0.66     56937
weighted avg       0.77      0.77      0.77     56937

[[22322    33   503  2815]
 [  272   382   444   252]
 [ 1257    64  4596  2352]
 [ 3749    32  1149 16715]]


([0.7730474032702812], array([1, 4, 4, ..., 1, 3, 1], dtype=int64))

In [45]:
from joblib import dump

dump(model, "save_model/model_gravite.joblib")

['save_model/model_gravite.joblib']

In [79]:
d_test = pd.DataFrame([[22, 3, 90.0, 1, 1.0, '94', 7, 11, 1.0, 1.0, 1.0, 1.0, 3, 1.0, 5.0, 1]], columns=data_train.columns)

In [81]:
d_test = full_pipeline.transform(d_test)
model.predict(d_test)

array([1], dtype=int64)